/* Code generated by the ForSyDe compiler */
#include "c-skeletons-for-SDF.c"


/* Function p1 */
void f_p1(token* in1, token* in2, token* out1){
	out1[0] = in1[0] + in1[1] + in2[0];
}

/* Function p2 */
void f_p2(token* in1, token* out1, token* out2){
	out1[0] = in1[0]; out2[0] = in1[0] + 1;
}

/* Function p4 */
void f_p4(token* in1, token* out1, token* out2){
	out2[0] = in1[0]; out2[1] = in1[0] + 1; out2[2] = in1[0] + 2; out1[0] = in1[0];
}

/* Function p5 */
void f_p5(token* in1, token* out1){
	out1[0] = in1[0] + 1;
}

/* Function p3 */
void f_p3(token* in1, token* in2, token* out1){
	out1[0] = in1[0] + in1[1]; out1[1] = in2[0] + in2[1];
}

int main(){
	token input;
	token output;
	token* buffer_sin = malloc(10 * sizeof(token));
	channel sin = createFIFO(buffer_sin, 10);

	token* buffer_s1 = malloc(3 * sizeof(token));
	channel s1 = createFIFO(buffer_s1, 3);

	token* buffer_s2 = malloc(3 * sizeof(token));
	channel s2 = createFIFO(buffer_s2, 3);

	token* buffer_s3 = malloc(3 * sizeof(token));
	channel s3 = createFIFO(buffer_s3, 3);

	token* buffer_s4 = malloc(3 * sizeof(token));
	channel s4 = createFIFO(buffer_s4, 3);

	token* buffer_s5 = malloc(3 * sizeof(token));
	channel s5 = createFIFO(buffer_s5, 3);

	token* buffer_s6 = malloc(3 * sizeof(token));
	channel s6 = createFIFO(buffer_s6, 3);
	/*Initial tokens for s6*/
	writeToken(s6, 0);
	writeToken(s6, 0);

	writeToken(sin, 1);
	writeToken(sin, 2);
	writeToken(sin, 3);
	writeToken(sin, 4);
	writeToken(sin, 5);
	writeToken(sin, 6);
	writeToken(sin, 7);
	writeToken(sin, 8);
	writeToken(sin, 9);
	writeToken(sin, 10);

	token* buffer_sout = malloc(3 * sizeof(token));
	channel sout = createFIFO(buffer_sout, 3);

	// while(1){
	for(int i = 0; i < 3; i++){

	// printf("Read 2 input tokens: ");
	// for(int j = 0; j <2; j++) {
	// 	scanf("%d", &input);
	// 	writeToken(sin, input);
	// }

	/* Actor p1 */
	actor21SDF(2,1, 1, &sin, &s6, &s1, f_p1);

	/* Actor p2 */
	actor12SDF(1, 1,1, &s1, &s2, &s3, f_p2);

	/* Actor p4 */
	actor12SDF(1, 1,3, &s2, &s4, &sout, f_p4);

	printf("Output:");
	for(int j = 0; j <3; j++) {
		readToken(sout, &output);
		printf("%d\n", output);
	}

	/* Actor p5 */
	actor11SDF(1, 1, &s4, &s5, f_p5);

	// printf("Read 2 input tokens: ");
	// for(int j = 0; j <2; j++) {
	// 	scanf("%d", &input);
	// 	writeToken(sin, input);
	// }

	/* Actor p1 */
	actor21SDF(2,1, 1, &sin, &s6, &s1, f_p1);

	/* Actor p2 */
	actor12SDF(1, 1,1, &s1, &s2, &s3, f_p2);

	/* Actor p4 */
	actor12SDF(1, 1,3, &s2, &s4, &sout, f_p4);

	printf("Output:");
	for(int j = 0; j <3; j++) {
		readToken(sout, &output);
		printf("%d\n", output);
	}

	/* Actor p5 */
	actor11SDF(1, 1, &s4, &s5, f_p5);

	/* Actor p3 */
	actor21SDF(2,2, 2, &s3, &s5, &s6, f_p3);
	}
	return 0;
}