/* Code generated by the ForSyDe compiler */
#include "c-skeletons-for-SY.c"

/* Function f */
int f(int a){
	int res;
	res = a; 
    for (int i = 0; i < 100000000; i++) { 
        res *= (-1); 
    }
	return res;
}

FILE *file;
Signal **sip;
Signal **s1;
Signal **s2;
Signal **s3;
Signal **sout;

void *loop0(void* arg)
{
	int input;
	int output;

	while(1)
	{		
		if(fscanf(file, "%d", &input) == 1) 
		{
			printf("Read 1 input tokens: ");
			printf("%d\n", input);
			
			// Allocate memory for Signal structure
            if(*sip == NULL)
			{
				*sip = (struct Signal *)malloc(sizeof(struct Signal));
				(*sip)->data = input;
				(*sip)->next = NULL;
			}
			else
			{
				struct Signal *current = *sip;
				while (current->next != NULL)
				{
					current = current->next;
				}
				current->next = (struct Signal *)malloc(sizeof(struct Signal));
				current->next->data = input;
				current->next->next = NULL;
			}
		}
	else {
			printf("End of file reached.\n");
			fclose(file);
			break;
		}
	}

	/* Vertex p1 */
	mapSY(f, *sip, s1);

	/* Vertex p2 */
	mapSY(f, *s1, s2);

	/* Vertex p3 */
	mapSY(f, *s2, s3);

	/* Vertex p4 */
	mapSY(f, *s3, sout);

	printf("Output:");
	struct Signal *current = *sout;
	while (current != NULL)
	{
		printf("%d\n", current->data);
		current = current->next;
	}
}

int main(int argc, char *argv[]) {
	// Check if the correct number of command-line arguments is provided
	if (argc != 2) {
		fprintf(stderr, "Usage: %s <filename>\n", argv[0]);
		return 1; // Return an error code
	}
	
	// Open the file for reading
	file = fopen(argv[1], "r");

	// Check if the file opened successfully
	if (file == NULL) {
		fprintf(stderr, "Unable to open the file '%s' for reading.\n", argv[1]);
		return 1; // Return an error code
	}

	// Allocate memory for Signal structure
	sip = (struct Signal **)malloc(sizeof(struct Signal *));
	*sip = NULL;
	s1 = (struct Signal **)malloc(sizeof(struct Signal *));
	*s1 = NULL;
	s2 = (struct Signal **)malloc(sizeof(struct Signal *));
	*s2 = NULL;
	s3 = (struct Signal **)malloc(sizeof(struct Signal *));
	*s3 = NULL;
	sout = (struct Signal **)malloc(sizeof(struct Signal *));
	*sout = NULL;

	loop0(NULL);

	return 0;
}